#!/bin/bash

file='elog.log';

let max=0;

for (( i=1; i <= 1000; i++ ))

do 

site=`cat elog.log | grep "http" | sed 's/.*\(.*http\)/\1/g' | sed 's/".*//' | head -n$i | tail -n1`

count=`grep $site $file | wc -l`


if [ $count -gt $max ];

then

let max=$count;

fsite=`cat elog.log | grep "http" | sed 's/.*\(.*http\)/\1/g' | sed 's/".*//' | head -n$i | tail -n1`

fi

done 

echo "Site - $fsite sum - $max"