#!/bin/bash

file='elog.log';

let max=0;

for (( i=1; i <= 1000; i++ ))

do 

site=`cat $file | grep "http" | sed 's/.*\(.*http\)/\1/g' | sed 's/".*//' | head -n$i | tail -n1 | awk -F[/:] '{print $4}'`

error=`cat $file | awk '{print $9}' | head -n$i | tail -n1 `

if [ $error = "404" ];

then

echo "Site with error - $site"

fi

done 

