#!/bin/bash

file='elog.log';

let max=0;

for (( i=1; i <= 1000; i++ ))

do 

site=`cat $file | grep "http" | sed 's/.*\(.*http\)/\1/g' | sed 's/".*//' | head -n$i | tail -n1 | awk -F[/:] '{print $4}'`

rm temp;

gsite=`grep $site $file >> temp`

rm temp1

timesort=`cat temp | awk '{print $4}' | awk -F[::] '{print $2}' | sort >> temp1`

count08=`grep 08 temp1 | wc -l` 

count09=`grep 09 temp1 | wc -l` 

count10=`grep 10 temp1 | wc -l` 

count11=`grep 11 temp1 | wc -l` 

count12=`grep 12 temp1 | wc -l` 

count13=`grep 13 temp1 | wc -l` 

count=$count08
rt='more requests at 8 am'

if [ $count09 -gt $count ];

then

count=$count09
rt='more requests at 9 am'

elif  [ $count10 -gt $count ];

then

count=$count10
rt='more requests at 10 am'

elif  [ $count11 -gt $count ];

then

count=$count11
rt='more requests at 11 am'

elif  [ $count12 -gt $count ];

then

count=$count12
rt='more requests at 12 am'

elif  [ $count13 -gt $count ];

then

count=$count13
rt='more requests at 13 am'


fi

echo "$site - $rt"

done 

#cat 123.log | awk '{print $4}' | sed -e 's/^..............//;s/......$//'
#grep https://www.google.co.uz 123.log | awk '{print $4}' | sed -e 's/^..............//;s/......$//' | wc -l