#!/bin/bash

file='elog.log';

let max=0;

for (( i=1; i <= 1000; i++ ))

do 

ip=`cat $file | awk '{print $1}' | head -n$i | tail -n1`

count=`grep $ip $file | wc -l`

echo "IP - $ip sum - $count"

done 

